### ISSUE TITLE
Would we want to change common.ResponseCore?

### ISSUE THREAD

**Issue by chelpu** [natebrennand/twiliogo#50]
To be more "common" to apply to all packages

**Comment by natebrennand** [comment]
I think so, or maybe make a variety of core responses.
Most of the account related endpoints had `FriendlyName` as an attribute.

**Comment by natebrennand** [comment]
yay for unix one liners `gsed -e '/struct {/,/}$/!d' **/*.go | pbcopy`

Here's every struct we declare in the project
https://gist.github.com/natebrennand/b4c40ef7f78666394b22

**Comment by natebrennand** [comment]
closing this for now given that we have `ResourceInfo` now
