### ISSUE TITLE
Could Next() be generalized to all "List" structures?

### ISSUE THREAD

**Issue by chelpu** [natebrennand/twiliogo#63]
Could we generalize structs with ListResponseCore, SpecificObject with an interface or something where the Next() method is already implemented? All Next() methods look exactly the same.

**Comment by natebrennand** [comment]
Unfortunately we can't declare a method on an interface, just on structs.
We could reduce it to one line for each of them, but I don't know if that's worth it. Given that they're all pretty brief as is, I think it might be ok how we have it

**Comment by chelpu** [comment]
Aight, fine by me. jw.
