### ISSUE TITLE
Add AccountSid to baseURL?

### ISSUE THREAD

**Issue by chelpu** [natebrennand/twiliogo#69]
It probably wouldn't be worth it at this point, but wouldn't it be possible to make the baseURL contain "/2010-04-01/Accounts/%s" and then just grab the account sid from the account that's being passed in with every SendGet, SendPost, etc?

**Comment by natebrennand** [comment]
We could move `/2010-04-01/Accounts/` into the base URL, that will require updating all of the `Next()` methods.
Unfortunately I'm not sure if we can also format the account sid string in there, there's [an endpoint](https://github.com/natebrennand/twiliogo/blob/master/accounts/account.go#L18) that doesn't use the account sid. This causes `fmt`'s formatter to add something along these lines `%!(EXTRA string=abc)` when you pass a parameter that doesn't have a string option for it.

**Comment by chelpu** [comment]
probably would cause more trouble than it would save at this point
